name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # This triggers the deployment on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version if different

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (for React or similar projects)
      - name: Build project
        run: npm run build  # Use your project's build command here

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase deploy --only hosting
